### PR TITLE
Consistent URL hashing; multi-value headers

### PR DESCRIPTION
**Pull request by mbland**
Maintains parity with 18F/hmacauth#1. We should wait for that PR to go in before reviewing/submitting this one (unless you want to check it out for style ahead of time).

cc: @afeld and/or @adelevie, if you've the bandwidth.

### CODE REVIEW

**Comment by mbland** [comment]
OK, 18F/hmacauth#1 is in. I've kept this PR in tight sync with that one. Either of y'all mind taking a peek sometime?

**Comment by mbland** [comment]
cc: @ccostino

**Comment by ccostino** [comment]
Awesome work, thanks @mbland!

**Comment by mbland** [comment]
Thanks for the review, @ccostino!

**Pull request merged**
